/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.calculadoracompleta;

/**
 *
 * @author ikaro
 */
public class JCalculadoraCompleta extends javax.swing.JDialog {
    
    
    
    private double res;
    private double ent;

    /**
     * Creates new form JCalculadoraCompleta
     */
    public JCalculadoraCompleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        res=0;
        ent=0;
        resultado.setText(Double.toString(res));
        entrada.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultado = new javax.swing.JTextField();
        entrada = new javax.swing.JTextField();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        butDividir = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        butSubtrair = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        butMultiplicar = new javax.swing.JButton();
        butPonto = new javax.swing.JButton();
        but0 = new javax.swing.JButton();
        butIgual = new javax.swing.JButton();
        butSomar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jcalc");

        resultado.setEditable(false);
        resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        but1.setText("1");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });

        but2.setText("2");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setText("3");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        butDividir.setText("/");
        butDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDividirActionPerformed(evt);
            }
        });

        but4.setText("4");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });

        but5.setText("5");
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });

        but6.setText("6");
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });

        butSubtrair.setText("-");
        butSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSubtrairActionPerformed(evt);
            }
        });

        but7.setText("7");
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });

        but8.setText("8");
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });

        but9.setText("9");
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });

        butMultiplicar.setText("*");
        butMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMultiplicarActionPerformed(evt);
            }
        });

        butPonto.setText(",");
        butPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPontoActionPerformed(evt);
            }
        });

        but0.setText("0");
        but0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but0ActionPerformed(evt);
            }
        });

        butIgual.setText("=");
        butIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butIgualActionPerformed(evt);
            }
        });

        butSomar.setText("+");
        butSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSomarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(but1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butDividir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(butPonto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(but0))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(but4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(but5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(but7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(but8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(but6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(butSubtrair))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(but9)
                                            .addComponent(butIgual))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(butMultiplicar)
                                            .addComponent(butSomar))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but1)
                    .addComponent(but2)
                    .addComponent(but3)
                    .addComponent(butDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but4)
                    .addComponent(but5)
                    .addComponent(but6)
                    .addComponent(butSubtrair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but7)
                    .addComponent(but9)
                    .addComponent(butMultiplicar)
                    .addComponent(but8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butPonto)
                    .addComponent(but0)
                    .addComponent(butIgual)
                    .addComponent(butSomar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSomarActionPerformed
        // TODO add your handling code here:
        
        ent = Double.parseDouble(entrada.getText());
        res = res + ent;
        entrada.setText("");
        resultado.setText(Double.toString(res));
        
    }//GEN-LAST:event_butSomarActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        // TODO add your handling code here:
        
        String temp;
        temp = entrada.getText();
        entrada.setText(temp + "1");
    }//GEN-LAST:event_but1ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "7");        // TODO add your handling code here:
    }//GEN-LAST:event_but7ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "2");        // TODO add your handling code here:
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "3");        // TODO add your handling code here:
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "4");        // TODO add your handling code here:
    }//GEN-LAST:event_but4ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "5");        // TODO add your handling code here:
    }//GEN-LAST:event_but5ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "6");        // TODO add your handling code here:
    }//GEN-LAST:event_but6ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "8");        // TODO add your handling code here:
    }//GEN-LAST:event_but8ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
 String temp;
        temp = entrada.getText();
        entrada.setText(temp + "9");        // TODO add your handling code here:
    }//GEN-LAST:event_but9ActionPerformed

    private void but0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but0ActionPerformed
String temp;
temp = entrada.getText();
if (temp.isEmpty() == false) entrada.setText(temp + "0");// TODO add your handling code here:
    }//GEN-LAST:event_but0ActionPerformed

    private void butPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPontoActionPerformed
String temp;
temp = entrada.getText();
if (temp.isEmpty() == false){
if (temp.contains(".")== false){
    entrada.setText(temp +".");
    
}}else{
entrada.setText("0.");}// TODO add your handling code here:
    }//GEN-LAST:event_butPontoActionPerformed

    private void butDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDividirActionPerformed
        // TODO add your handling code here:
        
        String temp;
        temp = entrada.getText();
        if (temp.isEmpty()) temp = "0";
        ent = Double.parseDouble(temp);
        if (ent !=0) {
            res = res/ent;
            entrada.setText("");
            resultado.setText(Double.toString(res));
}else{
            entrada.setText("");
            resultado.setText("Erro!");
            
        }
        
        
        
        
        
    }//GEN-LAST:event_butDividirActionPerformed

    private void butSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSubtrairActionPerformed
        // TODO add your handling code here:
        
        ent = Double.parseDouble(entrada.getText());
        res = res - ent;
        entrada.setText("");
        resultado.setText(Double.toString(res));
        
        
        
        
    }//GEN-LAST:event_butSubtrairActionPerformed

    private void butMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMultiplicarActionPerformed
        // TODO add your handling code here:
        
        ent = Double.parseDouble(entrada.getText());
        res = res * ent;
        entrada.setText("");
        resultado.setText(Double.toString(res));
        
        
    }//GEN-LAST:event_butMultiplicarActionPerformed

    private void butIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butIgualActionPerformed
        // TODO add your handling code here:
        String temp;
        temp = entrada.getText();
        if (temp .isEmpty())temp = "0";
        ent = Double.parseDouble(temp);
        res = ent;
        entrada.setText("");
        resultado.setText(Double.toString(res));
        
        
        
        
    }//GEN-LAST:event_butIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCalculadoraCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JCalculadoraCompleta dialog = new JCalculadoraCompleta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but0;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JButton butDividir;
    private javax.swing.JButton butIgual;
    private javax.swing.JButton butMultiplicar;
    private javax.swing.JButton butPonto;
    private javax.swing.JButton butSomar;
    private javax.swing.JButton butSubtrair;
    private javax.swing.JTextField entrada;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
